"version": 1.0
"project_base_dir": "./projects/"
"serifu_file": "serifu.txt"
"serifu_per_engine_file": "serifu_{0}.txt"
"jimaku_file": "jimaku.txt"
"raw_jimaku_file": "jimaku_raw.txt"
"input_dir": "input"
"output_dir": "output"
"rename_digits": 7
"renamed_output_dir": "all"
"supported_audio_file_ext":
  - ".wav"
  - ".mp3"
  - ".ogg"
"file_encoding":
  "serifu": "utf-8"
  "jimaku": "utf-8"
  "AIV": "utf-8"
  "AQ": "utf-8"
  "CA": "utf-8"
  "CC": "utf-8"
  "VP": "utf-8"
  "VR": "shift_jis"
  "VV": "utf-8"
  "VT": "utf-8"
  "NONE": "utf-8"
  "OTHER": "utf-8"
