"version": 1.0
"project_base_dir": './projects/'
"serifu_file": "serifu.txt"
"serifu_per_engine_file": "serifu_{0}.txt"
"jimaku_file": "jimaku.txt"
"raw_jimaku_file": "jimaku_raw.txt"
"rename_digits": 7
"renamed_output_dir": "all"
"supported_audio_file_ext":
  - ".wav"
  - ".mp3"
  - ".ogg"
"voice_engine":
  "AIV":
    "Name": "AI VOICE"
    "Separator": "＞"
  "AQ":
    "Name": "AquesTalk"
    "Separator": ","
  "CA":
    "Name": "CeVIO AI"
    "Separator": ","
  "CC":
    "Name": "CeVIO CS"
    "Separator": ","
  "VP":
    "Name": "VOICEPEAK"
    "Separator": ","
  "VR":
    "Name": "VOICEROID2"
    "Separator": "＞"
  "VV":
    "Name": "VOICEVOX"
    "Separator": ","
  "OTHER":
    "Name": "その他"
    "Separator": ","
  "NONE":
    "Name": "なし"
    "Separator": ","
"serifu_file_encoding": "utf-8"
"output_file_encoding":
  "jimaku": "utf-8"
  "AIV": "utf-8"
  "AQ": "utf-8"
  "CA": "utf-8"
  "CC": "utf-8"
  "VP": "utf-8"
  "VR": "shift_jis"
  "VV": "utf-8"
  "NONE": "utf-8"
  "OTHER": "utf-8"
"voice_actor":
  "栗田まろん": "AIV"
  "足立レイ": "AIV"
  "[AIV]琴葉 葵": "AIV"
  "琴葉 葵(蕾)": "AIV"
  "Aoi": "AIV"
  "葵": "AIV"
  "[AIV]琴葉 茜": "AIV"
  "琴葉 茜(蕾)": "AIV"
  "Akane": "AIV"
  "茜": "AIV"
  "伊織弓鶴": "AIV"
  "[AIV]伊織弓鶴": "AIV"
  "羽ノ華": "AIV"
  "羽ノ華(雫)": "AIV"
  "[AIV]結月ゆかり": "AIV"
  "結月ゆかり(雫)": "AIV"
  "[AIV]紲星あかり": "AIV"
  "紲星あかり(蕾)": "AIV"
  "紲星あかり(萌)": "AIV"
  "GUMI": "AIV"
  "結城 香": "AIV"
  "日ノ出賢": "AIV"
  "潮崎かずき": "AIV"
  "風見壮一": "AIV"
  "式狼縁": "AIV"
  "式大元": "AIV"
  "タンゲコトエ": "AIV"
  "ria": "AIV"
  "来果": "AIV"
  "咲ちゃん": "AIV"
  "青山龍星": "AIV"
  "若穂みのり": "AIV"
  "ゆっくり霊夢": "AQ"
  "博麗霊夢": "AQ"
  "ゆっくり魔理沙": "AQ"
  "霧雨魔理沙": "AQ"
  "小春六花": "CA"
  "ロサ(ROSA)": "CA"
  "[CA]さとうささら": "CA"
  "すずきつづみ": "CA"
  "[CA]すずきつづみ": "CA"
  "花隈千冬": "CA"
  "夏色花梨": "CA"
  "弦巻マキ": "CA"
  "IA": "CA"
  "[CA]IA": "CA"
  "ONE": "CA"
  "[CA]ONE": "CA"
  "弦巻マキ English": "CA"
  "さとうささら": "CC"
  "[CC]さとうささら": "CC"
  "[CC]すずきつづみ": "CC"
  "タカハシ": "CC"
  "[CC]IA": "CC"
  "[CC]ONE": "CC"
  "女性1": "VP"
  "女性2": "VP"
  "女性3": "VP"
  "女性4": "VP"
  "女の子": "VP"
  "男性1": "VP"
  "男性2": "VP"
  "男性3": "VP"
  "男性4": "VP"
  "男の子": "VP"
  "ずんだもん": "VP"
  "[VP]ずんだもん": "VP"
  "フリモメン": "VP"
  "東北ずん子": "VP"
  "彩澄しゅお": "VP"
  "彩澄りりせ": "VP"
  "京町セイカ": "VP"
  "琴葉 葵": "VR"
  "[VR]琴葉 葵": "VR"
  "琴葉 葵(v1)": "VR"
  "琴葉 茜": "VR"
  "[VR]琴葉 茜": "VR"
  "琴葉 茜(v1)": "VR"
  "結月ゆかり": "VR"
  "結月ゆかり(v1)": "VR"
  "紲星あかり": "VR"
  "桜乃そら": "VR"
  "京町セイカ(v1)": "VR"
  "[VR]伊織弓鶴": "VR"
  "[VR]東北ずん子(v1)": "VR"
  "[VR]東北きりたん(v1)": "VR"
  "[VR]東北イタコ": "VR"
  "水無瀬コウ(v1)": "VR"
  "民安ともえ(v1)": "VR"
  "鷹の爪 吉田くん(v1)": "VR"
  "月読アイ(v1)": "VR"
  "月読ショウタ(v1)": "VR"
  "ついなちゃん(標準語)": "VR"
  "ついなちゃん(関西弁)": "VR"
  "四国めたん": "VV"
  "四国めたん(ノーマル)": "VV"
  "四国めたん(あまあま)": "VV"
  "四国めたん(ツンツン)": "VV"
  "四国めたん(セクシー)": "VV"
  "四国めたん(ささやき)": "VV"
  "四国めたん(ヒソヒソ)": "VV"
  "[VV]ずんだもん": "VV"
  "ずんだもん(ノーマル)": "VV"
  "ずんだもん(あまあま)": "VV"
  "ずんだもん(ツンツン)": "VV"
  "ずんだもん(セクシー)": "VV"
  "ずんだもん(ささやき)": "VV"
  "ずんだもん(ヒソヒソ)": "VV"
  "春日部つむぎ": "VV"
  "雨晴はう": "VV"
  "波音リツ": "VV"
  "玄野武宏": "VV"
  "玄野武宏(ノーマル)": "VV"
  "玄野武宏(喜び)": "VV"
  "玄野武宏(ツンギレ)": "VV"
  "玄野武宏(悲しみ)": "VV"
  "白上虎太郎": "VV"
  "白上虎太郎(ふつう)": "VV"
  "白上虎太郎(わーい)": "VV"
  "白上虎太郎(びくびく)": "VV"
  "白上虎太郎(おこ)": "VV"
  "白上虎太郎(ぴえーん)": "VV"
  "青山龍星": "VV"
  "冥鳴ひまり": "VV"
  "九州そら": "VV"
  "九州そら(ノーマル)": "VV"
  "九州そら(あまあま)": "VV"
  "九州そら(ツンツン)": "VV"
  "九州そら(セクシー)": "VV"
  "九州そら(ささやき)": "VV"
  "九州そら(ヒソヒソ)": "VV"
  "もち子さん": "VV"
  "剣崎雌雄": "VV"
  "WhiteCUL": "VV"
  "WhiteCUL(ノーマル)": "VV"
  "WhiteCUL(たのしい)": "VV"
  "WhiteCUL(かなしい)": "VV"
  "WhiteCUL(ぴえーん)": "VV"
  "後鬼": "VV"
  "後鬼(人間ver.)": "VV"
  "後鬼(ぬいぐるみver.)": "VV"
  "No.7": "VV"
  "No.7(ノーマル)": "VV"
  "No.7(アナウンス)": "VV"
  "No.7(読み聞かせ)": "VV"
  "ちび式じい": "VV"
  "櫻歌ミコ": "VV"
  "櫻歌ミコ(ノーマル)": "VV"
  "櫻歌ミコ(第二形態)": "VV"
  "櫻歌ミコ(ロリ)": "VV"
  "小夜/SAYO": "VV"
  "ナースロボ＿タイプＴ": "VV"
  "ナースロボ＿タイプＴ(ノーマル)": "VV"
  "ナースロボ＿タイプＴ(楽々)": "VV"
  "ナースロボ＿タイプＴ(恐怖)": "VV"
  "ナースロボ＿タイプＴ(内緒話)": "VV"
  "†聖騎士 紅桜†": "VV"
  "雀松朱司": "VV"
  "麒ヶ島宗麟": "VV"
  "[なし]": "NONE"
  "ナレーター": "NONE"
  "その他": "OTHER"
  "生声": "OTHER"
