"version": 1.0
"scenario_file": "serifu.txt"
"output_file": "serifu_{}.txt"
"jimaku_file": "jimaku.txt"
"voice_engine":
  "VV":
    "Name": "VOICEVOX"
    "Separator": ","
  "VR":
    "Name": "VOICEROID2"
    "Separator": "＞"
  "VP":
    "Name": "VOICEPEAK"
    "Separator": ","
  "CC":
    "Name": "CeVIO CS"
    "Separator": ","
  "CA":
    "Name": "CeVIO AI"
    "Separator": ","
"voice_actor":
  "四国めたん": "VV"
  "四国めたん(ノーマル)": "VV"
  "四国めたん(あまあま)": "VV"
  "四国めたん(ツンツン)": "VV"
  "四国めたん(セクシー)": "VV"
  "四国めたん(ささやき)": "VV"
  "四国めたん(ヒソヒソ)": "VV"
  "ずんだもん(ノーマル)": "VV"
  "ずんだもん(あまあま)": "VV"
  "ずんだもん(ツンツン)": "VV"
  "ずんだもん(セクシー)": "VV"
  "ずんだもん(ささやき)": "VV"
  "ずんだもん(ヒソヒソ)": "VV"
  "春部つむぎ": "VV"
  "雨晴はう": "VV"
  "波音リツ": "VV"
  "玄野武宏": "VV"
  "玄野武宏(ノーマル)": "VV"
  "玄野武宏(喜び)": "VV"
  "玄野武宏(ツンギレ)": "VV"
  "玄野武宏(悲しみ)": "VV"
  "白上虎太郎": "VV"
  "白上虎太郎(ふつう)": "VV"
  "白上虎太郎(わーい)": "VV"
  "白上虎太郎(びくびく)": "VV"
  "白上虎太郎(おこ)": "VV"
  "白上虎太郎(ぴえーん)": "VV"
  "青山龍星": "VV"
  "冥鳴ひまり": "VV"
  "九州そら": "VV"
  "九州そら(ノーマル)": "VV"
  "九州そら(あまあま)": "VV"
  "九州そら(ツンツン)": "VV"
  "九州そら(セクシー)": "VV"
  "九州そら(ささやき)": "VV"
  "九州そら(ヒソヒソ)": "VV"
  "もち子さん": "VV"
  "剣崎雌雄": "VV"
  "WhiteCUL": "VV"
  "WhiteCUL(ノーマル)": "VV"
  "WhiteCUL(たのしい)": "VV"
  "WhiteCUL(かなしい)": "VV"
  "WhiteCUL(ぴえーん)": "VV"
  "後鬼": "VV"
  "後鬼(人間ver.)": "VV"
  "後鬼(ぬいぐるみver.)": "VV"
  "No.7": "VV"
  "No.7(ノーマル)": "VV"
  "No.7(アナウンス)": "VV"
  "No.7(読み聞かせ)": "VV"
  "ちび式じい": "VV"
  "櫻歌ミコ": "VV"
  "櫻歌ミコ(ノーマル)": "VV"
  "櫻歌ミコ(第二形態)": "VV"
  "櫻歌ミコ(ロリ)": "VV"
  "小夜/SAYO": "VV"
  "ナースロボ＿タイプＴ": "VV"
  "ナースロボ＿タイプＴ(ノーマル)": "VV"
  "ナースロボ＿タイプＴ(楽々)": "VV"
  "ナースロボ＿タイプＴ(恐怖)": "VV"
  "ナースロボ＿タイプＴ(内緒話)": "VV"
  "琴葉 葵": "VR"
  "琴葉 茜": "VR"
  "結月ゆかり": "VR"
  "紲星あかり": "VR"
  "桜乃そら": "VR"
  "京町セイカ(v1)": "VR"
  "ずんだもん": "VP"
  "フリモメン": "VP"
  "東北ずん子": "VP"
  "女声1": "VP"
  "女声2": "VP"
  "女声3": "VP"
  "女の子": "VP"
  "男声1": "VP"
  "男声2": "VP"
  "男声3": "VP"
  "さとうささら": "CC"
  "小春六花": "CA"
  "ロサ(ROSA)": "CA"
